#!/usr/bin/env python3
"""build_registry.py -- generate the derived skill registry.

    ./scripts/build_registry.py --out registry.json
    ./scripts/build_registry.py --check registry.json

The registry is the machine-readable catalogue of what this library contains.
Everything downstream joins on it: the plugin marketplace, evaluation results,
deprecation, the README roster.

IT IS DERIVED. Nothing here is hand-authored, and the file must never be edited
by hand -- CI regenerates and compares. A hand-maintained catalogue becomes a
second source of truth that drifts from the agents it describes, which is the
failure this repository has already seen once (the README's "230+ agents" while
270 shipped).

Sources, in order of authority:

  agent .md frontmatter    the agents themselves, via the canonical YAML parser
  divisions.json           the division set
  git history              provenance (created, last modified, commit count)

WHAT IS DELIBERATELY ABSENT

  version         A number that only ever reads 1.0.0 is not information, it is
                  decoration. Versioning becomes meaningful in Phase 8, where
                  promotion is what bumps it. Until then content_hash IS the
                  version: it changes exactly when the agent changes.
  security_state  Phase 5. An "unknown" on every row would invite being read as
                  "checked and fine".
  eval_state      Phase 7, same reasoning.

Adding empty fields early teaches consumers to trust placeholders. They arrive
with the machinery that fills them.
"""
from __future__ import annotations

import argparse
import collections
import hashlib
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.corpus import REPO_ROOT, comparable, divisions, dump_json, git, read_corpus  # noqa: E402
from lib.frontmatter import parse  # noqa: E402
from inventory import slugify_lib_sh  # noqa: E402

SCHEMA_VERSION = "1.0.0"

# Frontmatter carried into the registry verbatim. `id` and `name` are handled
# separately because they are identity, not attributes.
CARRIED = ("description", "color", "emoji", "vibe", "tools", "author", "services")


def provenance() -> dict[str, dict]:
    """First commit, last commit and commit count for every tracked file.

    ONE `git log` pass over all history rather than a call per file: 270
    subprocess spawns costs ~30s on Windows, this costs under a second.
    """
    out = git(["log", "--all", "--reverse", "--name-only",
               "--format=%x00%H%x1f%aI", "--diff-filter=AMR"]).decode("utf-8", "replace")
    info: dict[str, dict] = {}
    commit = date = None
    for line in out.split("\n"):
        if line.startswith("\x00"):
            commit, date = line[1:].split("\x1f", 1)
            continue
        path = line.strip()
        if not path or commit is None:
            continue
        rec = info.get(path)
        if rec is None:
            info[path] = {"created": date, "last_modified": date, "commits": 1}
        else:
            rec["last_modified"] = date
            rec["commits"] += 1
    return info


def build(ref: str | None = None) -> dict:
    corpus = read_corpus(ref)
    prov = provenance()
    div_meta = json.loads(
        (REPO_ROOT / "divisions.json").read_bytes().decode("utf-8"))["divisions"]

    agents = []
    for path in sorted(corpus):
        raw = corpus[path]
        frontmatter, body, _ = parse(REPO_ROOT / path)
        stem = path.rsplit("/", 1)[-1][:-3]
        name = frontmatter.get("name", "")

        record = {
            "id": frontmatter.get("id"),
            "name": name,
            "division": path.split("/")[0],
            "path": path,
            # Both legacy namespaces, frozen. Consumers that predate `id` --
            # strategy/runbooks.json keys on the stem, the 14 converters key on
            # the name-slug -- keep resolving through these.
            "legacy_ids": {
                "filename_stem": stem,
                "name_slug": slugify_lib_sh(name),
            },
            "content_hash": hashlib.sha256(raw).hexdigest(),
            "body_words": len(body.split()),
            "byte_count": len(raw),
            "lifecycle": "active",
            "provenance": prov.get(path, {}),
        }
        for field in CARRIED:
            if field in frontmatter:
                record[field] = frontmatter[field]
        agents.append(record)

    per_division = collections.Counter(a["division"] for a in agents)
    return {
        "schema_version": SCHEMA_VERSION,
        "_note": ("GENERATED by scripts/build_registry.py -- do not edit by hand. "
                  "Regenerate with `./scripts/build_registry.py --out registry.json`; "
                  "CI fails if it is stale. Derived from agent frontmatter, "
                  "divisions.json and git history."),
        "summary": {
            "agents": len(agents),
            "divisions": len(per_division),
            "agents_per_division": dict(sorted(per_division.items())),
            "total_body_words": sum(a["body_words"] for a in agents),
            "with_tools": sum(1 for a in agents if "tools" in a),
            "with_author": sum(1 for a in agents if "author" in a),
            "with_services": sum(1 for a in agents if "services" in a),
        },
        "divisions": {
            name: {**meta, "agents": per_division.get(name, 0)}
            for name, meta in sorted(div_meta.items())
        },
        "agents": agents,
    }


def report_drift(prev: dict, cur: dict) -> None:
    old = {a["id"]: a for a in prev.get("agents", [])}
    new = {a["id"]: a for a in cur["agents"]}
    for aid in sorted(set(old) - set(new)):
        print(f"  REMOVED  {aid}  ({old[aid]['path']})", file=sys.stderr)
    for aid in sorted(set(new) - set(old)):
        print(f"  ADDED    {aid}  ({new[aid]['path']})", file=sys.stderr)
    for aid in sorted(set(old) & set(new)):
        changed = sorted(k for k in new[aid] if old[aid].get(k) != new[aid][k])
        if changed:
            print(f"  CHANGED  {aid}  ({', '.join(changed)})", file=sys.stderr)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--ref", help="git ref to build from (default: working tree)")
    ap.add_argument("--out", type=Path, help="write JSON here")
    ap.add_argument("--check", type=Path, help="regenerate and diff; exit 1 if stale")
    args = ap.parse_args()

    if args.check and args.out:
        ap.error("--check and --out are mutually exclusive")

    data = build(args.ref)
    s = data["summary"]

    if args.check:
        prev = json.loads(args.check.read_bytes().decode("utf-8"))
        if comparable(prev) == comparable(data):
            print(f"PASSED: {args.check} is current "
                  f"({s['agents']} agents, {s['divisions']} divisions).")
            return 0
        print(f"FAILED: {args.check} is stale.", file=sys.stderr)
        report_drift(prev, data)
        print("\nRegenerate with ./scripts/build_registry.py --out registry.json",
              file=sys.stderr)
        return 1

    payload = dump_json(data)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_bytes(payload)
        print(f"Wrote {args.out}", file=sys.stderr)
    else:
        sys.stdout.buffer.write(payload)

    print(f"  {s['agents']} agents across {s['divisions']} divisions", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
