#!/usr/bin/env python3
"""conversion_manifest.py -- hash every file convert.sh generates.

    ./scripts/conversion_manifest.py --out metrics/conversion-manifest.json
    ./scripts/conversion_manifest.py --check metrics/conversion-manifest.json
    ./scripts/conversion_manifest.py --from <dir> --out ...   # reuse a built tree

The manifest is a cross-platform contract: generated on one machine, verified on
another. It catches two different failures with one artifact.

  1. NON-DETERMINISM. Same source, different bytes. Locale-dependent sort order,
     timestamps, hash-seed-dependent iteration, text-mode newline translation.
     Behavioural evaluation of a non-reproducible artifact measures the build,
     not the skill.

  2. UNINTENDED RENDERER CHANGES. Editing a converter, or a frontmatter value it
     reads, changes generated bytes. That is often correct -- but it should be
     visible and deliberate, not discovered later by a consumer.

This is NOT committed build output. It records the hashes of generated files,
not the files themselves; the repository's "generated output is never committed"
rule is intact (see CONTRIBUTING.md). It is a lockfile, not an artifact.

Running convert.sh takes minutes on Windows because each agent costs several
process spawns; --from lets an already-built tree be reused.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.corpus import REPO_ROOT, comparable, dump_json  # noqa: E402

SCHEMA_VERSION = "1.0.0"


def build_tree(dest: Path) -> None:
    """Run every converter into `dest`. Never touches integrations/."""
    script = REPO_ROOT / "scripts" / "convert.sh"
    proc = subprocess.run(
        ["bash", str(script), "--out", str(dest)],
        cwd=REPO_ROOT, capture_output=True,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout.decode("utf-8", "replace")[-4000:])
        sys.stderr.write(proc.stderr.decode("utf-8", "replace")[-4000:])
        raise SystemExit("convert.sh failed")


def hash_tree(root: Path) -> dict:
    """Map tool -> {relative path: sha256}, sorted and deterministic.

    README.md is excluded: it is a tracked, hand-written file that convert.sh
    preserves rather than generates -- except under integrations/hermes, where
    build-hermes-plugin.py regenerates it. Excluding it everywhere keeps the
    manifest to genuinely generated content.
    """
    tools: dict[str, dict[str, str]] = {}
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(root).as_posix()
        tool, _, sub = rel.partition("/")
        if not sub or Path(sub).name == "README.md":
            continue
        tools.setdefault(tool, {})[sub] = hashlib.sha256(path.read_bytes()).hexdigest()
    return tools


def build(source: Path | None) -> dict:
    tmp = None
    try:
        if source is None:
            tmp = Path(tempfile.mkdtemp(prefix="conv-manifest-"))
            build_tree(tmp)
            source = tmp
        tools = hash_tree(source)
        return {
            "schema_version": SCHEMA_VERSION,
            "summary": {
                "tools": len(tools),
                "files": sum(len(v) for v in tools.values()),
                "files_per_tool": {k: len(v) for k, v in sorted(tools.items())},
            },
            "tools": tools,
        }
    finally:
        if tmp is not None:
            shutil.rmtree(tmp, ignore_errors=True)


def report_drift(prev: dict, cur: dict) -> None:
    old, new = prev.get("tools", {}), cur["tools"]
    for tool in sorted(set(old) | set(new)):
        o, n = old.get(tool, {}), new.get(tool, {})
        added, removed = sorted(set(n) - set(o)), sorted(set(o) - set(n))
        changed = sorted(f for f in set(o) & set(n) if o[f] != n[f])
        if not (added or removed or changed):
            continue
        print(f"  {tool}: {len(changed)} changed, {len(added)} added, "
              f"{len(removed)} removed", file=sys.stderr)
        for f in changed[:5]:
            print(f"      CHANGED  {f}", file=sys.stderr)
        for f in added[:5]:
            print(f"      ADDED    {f}", file=sys.stderr)
        for f in removed[:5]:
            print(f"      REMOVED  {f}", file=sys.stderr)
        if len(changed) + len(added) + len(removed) > 15:
            print("      ...", file=sys.stderr)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--from", dest="source", type=Path,
                    help="use an already-converted tree instead of running convert.sh")
    ap.add_argument("--out", type=Path, help="write JSON here")
    ap.add_argument("--check", type=Path, help="recompute and diff; exit 1 on drift")
    args = ap.parse_args()

    if args.check and args.out:
        ap.error("--check and --out are mutually exclusive")

    data = build(args.source)
    s = data["summary"]

    if args.check:
        prev = json.loads(args.check.read_bytes().decode("utf-8"))
        if comparable(prev) == comparable(data):
            print(f"PASSED: conversion output matches {args.check} "
                  f"({s['files']} files across {s['tools']} tools).")
            return 0
        print(f"FAILED: conversion output differs from {args.check}.", file=sys.stderr)
        report_drift(prev, data)
        print("\nIf this change is intended, regenerate the manifest and say so in "
              "the commit message.", file=sys.stderr)
        return 1

    payload = dump_json(data)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_bytes(payload)
        print(f"Wrote {args.out}", file=sys.stderr)
    else:
        sys.stdout.buffer.write(payload)

    print(f"  {s['files']} files across {s['tools']} tools", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
